### ISSUE TITLE
Check invariant: addresses should not appear more than once, even across project files

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/oss-directory#28]
I think we found this in OSO, but not sure

**Comment by ryscheng** [comment]
Added the validation logic here
https://github.com/hypercerts-org/oss-directory/pull/42

Now just need to actually fix all the data issues

**Comment by ryscheng** [comment]
@ccerv1 Gonna leave this open until we can fix up the remaining issues in 
https://github.com/hypercerts-org/oss-directory/pull/42

Could I get your help with that?

**Comment by ccerv1** [comment]
The PR finally passed all the checks and I merged it 🚀
