### ISSUE TITLE
Quickly create a new collection + projects from a JSON list

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/oss-directory#36]
We currently have two approaches:
- https://github.com/hypercerts-org/oss-directory/blob/main/src/scripts/decouple-optimism-json.ts
- https://github.com/hypercerts-org/oss-directory/blob/main/src/scripts/collection-from-json-list.ts

We should create a more general, flexible ingestion script.

**Comment by ccerv1** [comment]
#37

**Comment by ryscheng** [comment]
I don't think this is a feasible issue. JSON is inherently too flexible with no structure. Without a schema, there's no way to tell what should go where, so I don't see a world where we can ever create a more general-purpose ingestion script. If there's no schema, we are forced to write custom scripts per possible format you'd get. Rather, I'd encourage folks to use oss-directory as a library, which has nice utilities like `safeCast` that allows you to conform to the existing schema.
