### ISSUE TITLE
OSS Project URL Errors

### ISSUE THREAD

**Issue by ravenac95** [hypercerts-org/oss-directory#63]
The following projects have issues with their project URLs (both 404):

* [poolfish-xyz](https://github.com/hypercerts-org/oss-directory/blob/9df725332f47ae5dae3ab584a3d8c111ed571e6f/data/projects/p/poolfish-xyz.yaml#L5)
* [nested](https://github.com/hypercerts-org/oss-directory/blob/9df725332f47ae5dae3ab584a3d8c111ed571e6f/data/projects/n/nested.yaml#L5)

**Comment by ccerv1** [comment]
#65
